### ISSUE TITLE
Are you open for changes and pull requests?

### ISSUE THREAD

**Issue by igromanru** [AntoniX35/Weapon-Swap-Stuttering-Fix#1]
Hi AntoniX35,
I like the mod, it's really helpful, especially in combination with my mod [Zero Weight](https://www.nexusmods.com/starfield/mods/3475) mod. With thousands items in my inventory my game were stuttering as hell while switching between weapons or even shooting full auto.  
I would like to contribute and replace the relative offset to a static address with a pattern search, that will persist a lot of game updates without further changes or extra dependencies.  
Here is an example of how it works: https://github.com/igromanru/SF-Zero-Weight/blob/a4760175e1f1e4f86a016f13281e13087b5b9698/Plugin/src/main.cpp#L47C10-L47C10

**Comment by AntoniX35** [comment]
Hello. I am aware of Assembly::search_pattern and have used it.
I got an SFSE error: the mod is not compatible with game verison.

**Comment by igromanru** [comment]
I just made the Pull Request, you can review it and/or clone the fork and test it out, if you want.  

I see you edited your message. With pattern scan the SFSE error won't come anymore. 
With the latest version v0.1.3 SFSE is finally checking for `addressIndependence` flag. It wasn't implemented before.  
With `UsesSigScanning(true)` or `UsesAddressLibrary(true)` in combination with `HasNoStructUse(true)` or `IsLayoutDependent(true)` it won't prevent your mod from loading after future game updates. Because it assumes that you get your addresses dynamically and does not use game structures that might change.

**Comment by igromanru** [comment]
Okey, I think I can close now.
