### ISSUE TITLE
Concern about unforeseen consequences

### ISSUE THREAD

**Issue by igromanru** [AntoniX35/Weapon-Swap-Stuttering-Fix#4]
As I made my PR with pattern scan it caught my attention, but I dismissed it because it seems to work, that you patch out a Jump that leads outside of the function.  
What exactly happens after that?  
Because the code goes through all the nop and inside the next function, which can't be good.
You know the code, but you can see it here in CE memory view:
![cheatengine-x86_64-SSE4-AVX2_RX9vkbujYv](https://github.com/AntoniX35/Weapon-Swap-Stuttering-Fix/assets/1902937/95419c1b-22ca-4168-8b35-d12956ce0cb3)
In IDA Pro you can see it even better, the jump leaves the function and the code below is already another function.
![ida64_hHtrbMUpzQ](https://github.com/AntoniX35/Weapon-Swap-Stuttering-Fix/assets/1902937/eedc954f-2818-421c-89e1-8f20d3d274ef)

People in the nexus comments and reddit are already reporting that they have sometimes weird behavior with stats. This is the reason why I had to think about it again. However, as I tried it out today, my breakpoint were never triggered in the function there, so I guess BSG has indeed patcht it with the last patch.

**Comment by AntoniX35** [comment]
This is the address of a different version of the game.

**Comment by AntoniX35** [comment]
I added 2 new fixes, the second one is in doubt - new bugs may appear. I will test the first fix for 1-2 days.
1 - Fix for stuttering when shooting with a large number of items in the inventory
2 - Less stuttering for uncommon weapons, i.e. just like switching between common weapons.  Not sure if it's needed.

**Comment by igromanru** [comment]
But this version is currently not released right?  
However, I personally don't need the mod anymore since the last game update. And I have about a hundred thousand items in my inventory, like at least 10k of each resource I mine from outposts (I'm using the Zero Weight mod).   
Maybe people with low specs still do.  
Since you're aware, I'm closing the issue.

**Comment by AntoniX35** [comment]
Haven't published yet. Need to test it properly.

**Comment by AntoniX35** [comment]
Have you encountered such a bug? Is there a big FPS drop when shooting? The bug appears if you carry a lot of things.

**Comment by igromanru** [comment]
I have to correct myself. The stuttering still exists with very high fire rate weapons like Macrogun.  
I run a Stealth build, using sniper and a typical Assault Rifles and since the last game update the stuttering is hardly noticeable with these weapons, not like before.  
But as I took out the Macrogun, the FPS is sinking hard during the shooting. So the mod is indeed still necessary.

Do you want me to test out the current mod version from the source as well, before you release it on nexus?

EDIT: So I watched the FPS counter. There is no more stuttering for me, but the FPS sinks brutally. I use DLSS with Frame Generation mod and the games runs on my hardware which includes the RTX 4080 almost constantly with 144fps.  
When I shoot the macrogun without the mod fix, the FPS drops to 30 fps. With normal rifle under 150 fire rate the FPS drops to like 120 while I'm firing.

**Comment by AntoniX35** [comment]
Yeah, it would be great.  Make a separate save before installing the mod (Just in case). I don’t recommend using it on the main save yet.
